local path = minetest.get_modpath("skytest")
dofile(path.."/craft_Items.lua")
dofile(path.."/nodes.lua")
dofile(path.."/tools.lua")
dofile(path.."/compost_bin.lua")
dofile(path.."/infused_soil.lua")
dofile(path.."/sieve.lua")
dofile(path.."/crucible.lua")
dofile(path.."/advanced_compostbin.lua")
dofile(path.."/achievement_book.lua")
dofile(path.."/wings.lua")
dofile(path.."/jetpack.lua")
dofile(path.."/storage.lua")